### ISSUE TITLE
Install failed on macOS 10.13.2

### ISSUE THREAD

**Issue by Fangyh09** [Angelmmiguel/pm#13]
Cannot install it on macOS 10.13.2
```bash
./install.sh
```
And I got
```bash
Hello! I'm here to help you to install PM
What's your shell? [ zsh ]: yes
Installing v0.4 version...
Now, your console isn't available :(. Create an issue on: https://github.com/Angelmmiguel/pm/issues.
```

**Comment by Angelmmiguel** [comment]
Hello @Fangyh09,

Sorry for the confusion. The input expects a value from the array. Instead of `yes`, the response should be `zsh`:

```
Hello! I'm here to help you to install PM
What's your shell? [ zsh ]: zsh
```

In the past, I planned to support more than one shell. However, I decided to support only `zsh` so it doesn't make sense to continue showing that input. I'll remove it from the project.

Could you check if the installation is fine using the `zsh` value? 

Thanks!

**Comment by Angelmmiguel** [comment]
I'm going to close this issue. Please, reopen it in case you cannot make it work :)

**Comment by Fangyh09** [comment]
@Angelmmiguel Okay~
